config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # 犬投稿のルーティング
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    
    # 一覧表示
    def index
        # 全て表示
        @dog = Dog.all
    end
    # 投稿新規画面
    def new
        # インスタンス作成
        @dog = Dog.new
    end

    # 投稿処理
    def create
        # フォームから送信されたパラメータを基に新しいDogを作成
        @dog = Dog.new(dog_params)

        # 保存処理
        if @dog.save
            puts "保存成功: リダイレクトを実行します"
            # 成功後、詳細ページにリダイレクト
            redirect_to dogs_path
        else
            puts "保存成功: リダイレクトを実行します"
            # 失敗した場合は新規投稿画面を再表示
            render :new
        end
    end

    ## ストロングパラメータ
    private

    # Strong Parameters で許可するパラメータを指定
    def dog_params
        params.require(:dog).permit(:name, :breed, :age, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<h1>犬の投稿一覧</h1>
<%= link_to '新規投稿', new_dog_path %>
<ul>
  <% @dog.each do |dog| %>
    <li>
      <%= link_to dog.name, dog %>
      <%= link_to dog.description, dog %>
      <%= link_to dog.age, dog %>
      <%= link_to dog.breed, dog %>
      <%= link_to dog.image, dog %>
      <%= link_to '編集', edit_dog_path(dog) %> |
      <%= link_to '削除', dog, method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </li>
  <% end %>
</ul>

app/views/dogs/new.html.erb
<%= form_with model: @dog, local: true do |form| %>
    <%= form.label :name, '名前' %>
    <%= form.text_field :name %><br>
  
    <%= form.label :description, '説明' %>
    <%= form.text_area :description %><br>

    <%= form.label :age, '年齢' %>
    <%= form.text_area :age %><br>

    <%= form.label :breed, '内容' %>
    <%= form.text_area :breed %><br>
  
    <%= form.label :image, '画像URL' %>
    <%= form.text_field :image %><br>
  
    <%= form.submit %>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>